### ISSUE TITLE
Nuget package dependency incorrect version..

### ISSUE THREAD

**Issue by srininz77** [BalassaMarton/MSBump#11]
I have 2 projects - ProjectA and ProjectB.

I added MSBump nuget package to both the projects. I have the following version in both csproj files:
1.0.0-pre000002

ProjectB has dependency on ProjectA.

When I build the solution, the version number in both the projects are incremented to 1.0.0-pre000003 which is CORRECT.

However, the resulting ProjectB nuget package has dependency on ProjectA nuget package 1.0.0-pre000002 instead of 1.0.0-pre000003.

Any ideas why this is happening. Thank you.

**Comment by BalassaMarton** [comment]
@srininz77 Thank you for reporting this problem. It is actually an issue with NuGet: NuGet/Home#4337
Until this is resolved, the only workaround I have is to run `dotnet build --no-dependencies` manually on your projects.

**Comment by srininz77** [comment]
Thanks.
A post build event of dotnet pack --no-build worked for me.

**Comment by BalassaMarton** [comment]
I've reopened this issue so that others can find the workaround more easily. I'll close it when the blocking NuGet issue is fixed.

**Comment by BalassaMarton** [comment]
@srininz77 I've added your workaround to the readme. As it turns out, NuGet/Home#4790 is the blocking issue.

**Comment by achandlerwhite** [comment]
Hi, using 2.3.2 even with @srininz77's workaround I see the problem behavior. I also noticed thats the deps.json file in the output directory appears to be ahead by 1:
```
...
"targets": {
    ".NETStandard,Version=v2.0": {},
    ".NETStandard,Version=v2.0/": {
        "MyProject/1.0.0-dev0007": {
            "dependencies": {
              "MyProject.Core": "1.0.0-dev0006",
...
```
In the .csproj file both MyProject and MyProject.Core had version 1.0.0-dev0006 before build and version 1.0.0-dev0007 after build. It seems like a mismatch in the json selection above.

Thanks!

**Comment by BalassaMarton** [comment]
@achandlerwhite could you please create a repo to demonstrate the problem?

**Comment by achandlerwhite** [comment]
@BalassaMarton sure here it is: https://github.com/achandlerwhite/MSBumpExample
