### ISSUE TITLE
Copy the generated nuget package to a local nuget directory

### ISSUE THREAD

**Issue by XdX-Software** [BalassaMarton/MSBump#16]
Hi,

can you help me to copy the generated nuget package file to a local nuget directory (NuGet Feed)?

**Comment by OriginalSINe** [comment]
You want the _add_ command: https://docs.microsoft.com/en-us/nuget/tools/cli-ref-add

If you're using MSBuild targets, MSBump is a little finicky with multi-targeted solutions. 

Here's my .targets file for it:
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="PackForBump" AfterTargets="MSBumpAfterOuterBuild">
    <Exec Command="dotnet pack --no-build -c $(Configuration)"/>
  </Target>
  <Target Name="NuGetAddPostPack" AfterTargets="PackForBump">
    <Exec Command="nuget.exe add $(ProjectDir)bin\$(Configuration)\$(PackageId).$(PackageVersion).nupkg -Source &quot;S:\packages&quot;" />
  </Target>
</Project>
```
Be sure to replace the `S:\packages `with whatever your local feed is!

For single target solutions, you will have to change `AfterTargets="MSBumpAfterOuterBuild"`. I believe I had it working as `AfterTargets="AfterBuild"`

**Comment by XdX-Software** [comment]
Thank you very much, that ist exactly what I needed!
One last thing, I don't know if this is possible at all.

But the "S:\packges" thing is in a multi user project a bit dirty 😃 
Is it possible to replace it with something more dynamic like "%USER_DIR%\nuget-feed" or so?

**Comment by OriginalSINe** [comment]
Yep, with properties. 

You can define properties in a couple places:
- properties in your project file (ie, .csproj): https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-properties
- properties in a Directory.Build.props: https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build
- Environmental variables

S:\packages is a network drive, and all my projects share a single Directory.Build.targets (which are very useful!)

**Comment by XdX-Software** [comment]
Thank you very much! 15 years in the business and every day something new 😃 
This "issue" can be closed.
