### ISSUE TITLE
May or may not want to add Xml Encoding

### ISSUE THREAD

**Issue by mwpowellhtx** [BalassaMarton/MSBump#20]
The default *VS2017 CSPROJ* appears to not care about encoding at all. However, when, apparently, your code touches the file for the ``Version``, you are adding:

```Xml
<?xml version="1.0" encoding="utf-8"?>
```

This may or may not be a concern? I don't know...

**Comment by BalassaMarton** [comment]
It's optional but perfectly standard. In fact, UTF-8 is the default encoding, so any XML parser would assume the exact same XML declaration if it isn't there.

**Comment by mwpowellhtx** [comment]
I know it's standard, technically speaking; I'm not sure that the VS bits are expecting it. That's my point.
