### ISSUE TITLE
The "MSBump.BumpVersion" task could not be loaded from the assembly

### ISSUE THREAD

**Issue by ryanbuening** [BalassaMarton/MSBump#3]
Hello. I'm trying to use MSBump for a NuGet package that is targeting .NET Standard 2.0. I am able to build the project and it increments the version successfully. However, when I go to the Package Manager Console to run a `dotnet pack`  command I get the following errror:

C:\Users\name\.nuget\packages\msbump\2.1.0\build\MSBump.targets(6,9): error MSB4062: The "MSBump.BumpVersion" task could not be loaded from the assembly C:\Users\name\.nuget\packages\msbum
p\2.1.0\build\..\tools\MSBump\MSBump.dll. Could not load file or assembly 'MSBump, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null'. Confirm that the <UsingTask> declaration is correct, th
at the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\VisualStudioProjects\PackageName\PackageName\PackageName\PackageName.csproj]

Any ideas? Am I doing something wrong?

**Comment by BalassaMarton** [comment]
@ryanbuening Can you post your .csproj file? Are you using MSBuild 15? Looks like a property did not get evaluated correctly.

**Comment by ryanbuening** [comment]
@BalassaMarton I changed the <GeneratePackageOnBuild /> property from false to true so I don't need to run the `dotnet pack` command. This successfully generated my NuGet package with the updated version. Thanks.

**Comment by BalassaMarton** [comment]
OK, I'm working on a new release that is more easy to use, and eliminates project file editing completely. Should be out within 24 hours...
