### ISSUE TITLE
Get version number while application is running

### ISSUE THREAD

**Issue by tommytayman** [BalassaMarton/MSBump#30]
I believe I have this setup correctly but my question is when using MSBump, can you get a reference to the assembly version number that you have set or is this outside the scope of this library?

**.msbump JSON file**

```
{
  "Configurations": {
    "Debug": {
      "BumpLabel": "local",
      "LabelDigits": 6
     },
    "QA - Dev": {
      "BumpLabel": "dev",
      "LabelDigits": 6
    },
    "Release": {
      "BumpPatch": true,
      "ResetLabel": "dev"
    }
  }
}
```
**.csproj file after compile** (note, the version number being placed in the .csproj)

```
  <PropertyGroup>
    <Version>1.19.0-local000001</Version>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProductVersion></ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
```
**AssemblyInfo.cs in project**
```
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("UI")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("UI")]
[assembly: AssemblyCopyright("Copyright ©  2019")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]

[assembly: Guid("6cb0f8c7-14c6-441e-8c6b-c7cb84ca1abb")]
// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
```

**Attempt to read version number of assembly**

`return Assembly.GetExecutingAssembly().GetName().Version.ToString();`

This last return always returns `0.0.0.0` when I would expect (or trying to find out how) to have a function return the value `1.19.0-local000001`.  I have seen issue #23 and it appears its a similar question but I cannot tell what the resolution was from the comments.  I removed the `AssemblyVersion` attribute baed on what it looks like the conversation was hinting at but to no avail, the same results are returned. 

What part am I missing?

**Comment by HendrikFW** [comment]
This code works for me, You can get the version you expect with:

```cs
var Version = typeof(<SomeClass>).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>().InformationalVersion;
```

Replace <SomeClass> with the name of any of your classes within the versioned assembly.

**Comment by tommytayman** [comment]
@HendrikFW - thanks for the code snippet!  I'll put this in today or tomorrow and give it a whirl

**Comment by tommytayman** [comment]
@HendrikFW - After a lot of education on MSBuild files, I've come to the determination that this is only for .Net Core projects and not .Net Framework projects (even though I'm using VS2017).  Thanks for the assistance, but I think I have to stick with the [1.0.*] method in the AssemblyInfo.cs.
