### ISSUE TITLE
Build errors on latest version

### ISSUE THREAD

**Issue by dasjestyr** [BalassaMarton/MSBump#5]
I've updated to the latest package and projects will no longer build. They each output the following errors

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	MSB4064	The "Configuration" parameter is not supported by the "BumpVersion" task. Verify the parameter exists on the task, and it is a settable public instance property.	DAS.Infrastructure	C:\Users\jstafford\.nuget\packages\msbump\2.2.0\build\MSBump.targets	9	

and

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	MSB4063	The "BumpVersion" task could not be initialized with its input parameters. 	DAS.Infrastructure	C:\Users\jstafford\.nuget\packages\msbump\2.2.0\build\MSBump.targets	8	

I saw that the nuget package now uses a settings file, so I created a file that has the same name as the csproj file but with a msbump extension but no luck:

``` javascript
{
	"Configurations": {
		"Debug": {
			"BumpLabel": "dev"
		},
		"Release" : {
			"BumpResetLabel": "dev",
			"BumpRevision": true
		}
	}
}
```

this is what MSBump.targets looks like in the IDE

![image](https://user-images.githubusercontent.com/3200529/29471425-d1536752-8404-11e7-90d2-e349c3fab5a2.png)

Any ideas?

**Comment by BalassaMarton** [comment]
@dasjestyr have you tried deleting the msbump directory from the package cache? I had the same problem, but then I deleted it, reinstalled the package, and everything worked.

**Comment by dasjestyr** [comment]
Oh that appears to have done it. Thanks!
