### ISSUE TITLE
netstandard 2.0

### ISSUE THREAD

**Issue by disophisis** [BalassaMarton/MSBump#6]
Is there anything preventing this from being moved to netstandard?

**Comment by BalassaMarton** [comment]
@disophisis not that I know of, I'll look into it in a few days. Could take some experimenting, because I never did this before.

**Comment by dasjestyr** [comment]
I was just about to create an issue for this. All things considered, I thought it would port just fine, but I keep running into these build errors on every project that uses MSBump:

> C:\Users\jstafford\.nuget\packages\msbump\2.2.0\build\MSBump.targets(8,9): error MSB4062: The "MSBump.BumpVersion" task could not be loaded from the assembly C:\Users\jstafford\.nuget\packages\msbump\2.2.0\build\..\tools\MSBump\MSBump.dll. Could not load file or assembly 'MSBump, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null'. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\source\das\platform\forks\das.infrastructure\src\standard\das.practices\das.practices.csproj]

**Comment by BalassaMarton** [comment]
Yes, looks like I really have to multi-target the tasks. I'm already working on it...

**Comment by BalassaMarton** [comment]
After the latest Visual Studio update, `dotnet build` does throw any errors for me. But the task doesn't get executed either, so it's still not working as expected.

**Comment by BalassaMarton** [comment]
Looks like the issue is with the `Newtonsoft.Json` dependency, removing it solves it (but I can't remove it unless I drop the `.msbump` file support).

**Comment by BalassaMarton** [comment]
The new `2.3.0` version is now [available on NuGet](https://www.nuget.org/packages/MSBump/2.3.0). It targets `netstandard1.6` and `net46`, and works with `dotnet build` (at least with the latest VS updates).

**Comment by disophisis** [comment]
This appears to be working a-ok for me.  I'm going to close this for now and if anyone has anything else to add, we can reopen it. Thanks!
