### ISSUE TITLE
FileVersion and AssemblyVersion

### ISSUE THREAD

**Issue by peters** [BalassaMarton/MSBump#9]
Hi,

```
<Version>78.0.0.27</Version>
<AssemblyVersion>58.0.0.0</AssemblyVersion>
<FileVersion>58.0.0.0</FileVersion>
```

```
    <ItemGroup Condition="'$(TargetFramework)' == 'net47'">
        <Reference Include="System" />
        <Reference Include="System.Core" />
    </ItemGroup>
    <PropertyGroup Condition=" '$(Configuration)'=='Debug' ">
        <ResetMinor>True</ResetMinor>
        <ResetPatch>True</ResetPatch>
        <BumpLabel></BumpLabel>
        <BumpRevision>True</BumpRevision>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)'=='Release' ">
        <ResetMinor>True</ResetMinor>
        <ResetPatch>True</ResetPatch>
        <ResetRevision>True</ResetRevision>
        <BumpMajor>True</BumpMajor>
    </PropertyGroup>
```

Building in `Release` mode I expect `Version`, `AssemblyVersion`, `FileVersion` in my `.csproj` project file to be `79.0.0.0`. `Version` is `82.0.0.27` (https://github.com/BalassaMarton/MSBump/issues/8) `but `AssemblyVersion` and `Version` is `58.0.0.0`. 

Log output:

```
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Build started: Project: MongoMigrations, Configuration: Release Any CPU ------
1>Changing project version to 80.0.0.27...
1>Changing project version to 81.0.0.27...
1>Changing project version to 82.0.0.27...
1>MongoMigrations -> C:\Users\peters\Documents\GitHub\dotnetmongomigrations\src\MongoMigrations\bin\Release\net47\MongoMigrations.dll
1>MongoMigrations -> C:\Users\peters\Documents\GitHub\dotnetmongomigrations\src\MongoMigrations\bin\Release\netstandard2.0\MongoMigrations.dll
1>MongoMigrations -> C:\Users\peters\Documents\GitHub\dotnetmongomigrations\src\MongoMigrations\bin\Release\netcoreapp2.0\MongoMigrations.dll
1>Successfully created package 'C:\nupkgs\MongoMigrations.79.0.0.27.nupkg'.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

Finally the `nupkg` is named `79.0.0.27` but this is tracked by https://github.com/BalassaMarton/MSBump/issues/8.

**Comment by BalassaMarton** [comment]
Yes, MSBump currently only modifies `Version` (also sets the `PackageVersion` property, but doesn't save it). This is a feature to be added.

**Comment by Esperadoce** [comment]
I have the same problem it was working but for some reason it's not saving it

**Comment by BalassaMarton** [comment]
I'm about to fix this, but I'm not sure what the expected behavior would be. If MSBump finds multiple version tags (eg. `Version`, `PackageVersion`, `AssemblyVersion`), should it bump them individually?

**Comment by BalassaMarton** [comment]
So basically we have to decide what to do with the `AssemblyVersion` and `FileVersion` properties.
1. Bump them individually. We need separate configuration options for each version property.
2. Overwrite them with the new value of `Version`. I don't see the point, because simply removing these properties will make MSBuild to use `Version` instead.

**Comment by dinobud** [comment]
@BalassaMarton I am in favor of keeping it how it is as there is no reason to use the other version properties since the "Version" property by itself is sufficient.
